//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "biz_showcase_profile")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub showcase_code: String,
    pub title: String,
    pub avatar: Option<String>,
    pub cover_image: Option<String>,
    pub contact_name: Option<String>,
    pub contact_gender: i16,
    pub contact_phone: Option<String>,
    pub contact_email: Option<String>,
    pub official_url: Option<String>,
    pub status: i16,
    pub featured: bool,
    pub priority: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub score: Option<Decimal>,
    pub publish_date: Option<Date>,
    pub launch_at: Option<DateTime>,
    pub service_time: Option<Time>,
    pub attachment_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extra_notes: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
