//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub config_name: String,
    #[sea_orm(unique)]
    pub config_key: String,
    #[sea_orm(column_type = "Text")]
    pub config_value: String,
    #[sea_orm(column_type = "Text")]
    pub default_value: String,
    pub value_type: i16,
    pub config_group: String,
    pub option_dict_type: String,
    pub config_sort: i32,
    pub enabled: bool,
    pub is_system: bool,
    pub remark: String,
    pub create_by: String,
    pub create_time: DateTime,
    pub update_by: String,
    pub update_time: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
