-- ============================================================
-- 自动生成的菜单数据
-- ============================================================

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (400, 0, 1, 'Widgets', '/widgets', '/index/index', '', 'ri:apps-2-add-line', 'menus.widgets.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (401, 400, 1, 'Icon', 'icon', '/widgets/icon', '', 'ri:palette-line', 'menus.widgets.icon', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (402, 400, 1, 'ImageCrop', 'image-crop', '/widgets/image-crop', '', 'ri:screenshot-line', 'menus.widgets.imageCrop', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (403, 400, 1, 'Excel', 'excel', '/widgets/excel', '', 'ri:download-2-line', 'menus.widgets.excel', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (404, 400, 1, 'Video', 'video', '/widgets/video', '', 'ri:vidicon-line', 'menus.widgets.video', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (405, 400, 1, 'CountTo', 'count-to', '/widgets/count-to', '', 'ri:anthropic-line', 'menus.widgets.countTo', '', false, false, false, false, false, false, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (406, 400, 1, 'WangEditor', 'wang-editor', '/widgets/wang-editor', '', 'ri:t-box-line', 'menus.widgets.wangEditor', '', false, false, false, false, false, true, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (407, 400, 1, 'Watermark', 'watermark', '/widgets/watermark', '', 'ri:water-flash-line', 'menus.widgets.watermark', '', false, false, false, false, false, true, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (408, 400, 1, 'ContextMenu', 'context-menu', '/widgets/context-menu', '', 'ri:menu-2-line', 'menus.widgets.contextMenu', '', false, false, false, false, false, true, false, false, '', '', '', '', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (409, 400, 1, 'Qrcode', 'qrcode', '/widgets/qrcode', '', 'ri:qr-code-line', 'menus.widgets.qrcode', '', false, false, false, false, false, true, false, false, '', '', '', '', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (410, 400, 1, 'Drag', 'drag', '/widgets/drag', '', 'ri:drag-move-fill', 'menus.widgets.drag', '', false, false, false, false, false, true, false, false, '', '', '', '', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (411, 400, 1, 'TextScroll', 'text-scroll', '/widgets/text-scroll', '', 'ri:input-method-line', 'menus.widgets.textScroll', '', false, false, false, false, false, true, false, false, '', '', '', '', 11, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (412, 400, 1, 'Fireworks', 'fireworks', '/widgets/fireworks', '', 'ri:magic-line', 'menus.widgets.fireworks', '', false, false, false, false, false, true, false, false, 'Hot', '', '', '', 12, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (413, 400, 1, 'ElementUI', '/outside/iframe/elementui', '', '', 'ri:apps-2-line', 'menus.widgets.elementUI', 'https://element-plus.org/zh-CN/component/overview.html', true, false, false, false, false, false, false, false, '', '', '', '', 13, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 重置序列
SELECT setval('sys_menu_id_seq', (SELECT MAX(id) FROM sys_menu));
