-- ============================================================
-- 自动生成的菜单数据 — Scheduler 模块（ID: 1000-1017）
-- ============================================================

CREATE SCHEMA IF NOT EXISTS sys;

-- 顶级菜单：调度
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1000, 0, 1, 'Scheduler', '/scheduler', '/index/index', '', 'ri:timer-line', 'menus.scheduler.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 14, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 子菜单：任务列表
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1001, 1000, 1, 'SchedulerJob', 'job', '/scheduler/job', '', 'ri:task-line', 'menus.scheduler.job', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 子菜单：执行历史
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1002, 1000, 1, 'SchedulerRun', 'run', '/scheduler/run', '', 'ri:history-line', 'menus.scheduler.run', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 子菜单：实例监控
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1003, 1000, 1, 'SchedulerInstance', 'instance', '/scheduler/instance', '', 'ri:server-line', 'menus.scheduler.instance', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 按钮权限：任务列表下的操作（挂在 SchedulerJob = 1001 下）
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1010, 1001, 2, '', '', '', '', '', '新增', '', false, false, false, false, false, false, false, false, '', '', '新增', 'add', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1011, 1001, 2, '', '', '', '', '', '编辑', '', false, false, false, false, false, false, false, false, '', '', '编辑', 'edit', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1012, 1001, 2, '', '', '', '', '', '删除', '', false, false, false, false, false, false, false, false, '', '', '删除', 'delete', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1013, 1001, 2, '', '', '', '', '', '启停', '', false, false, false, false, false, false, false, false, '', '', '启停', 'toggle', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1014, 1001, 2, '', '', '', '', '', '触发', '', false, false, false, false, false, false, false, false, '', '', '触发', 'trigger', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1015, 1001, 2, '', '', '', '', '', '批量', '', false, false, false, false, false, false, false, false, '', '', '批量', 'batch', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1016, 1001, 2, '', '', '', '', '', '依赖', '', false, false, false, false, false, false, false, false, '', '', '依赖', 'dependency', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1017, 1001, 2, '', '', '', '', '', '试运行', '', false, false, false, false, false, false, false, false, '', '', '试运行', 'dryrun', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 重置序列
SELECT setval('sys.menu_id_seq', (SELECT MAX(id) FROM sys.menu));