-- ============================================================
-- 前端菜单数据完整导入脚本
-- ============================================================

-- 清空表数据并重置 ID 序列
CREATE SCHEMA IF NOT EXISTS sys;

TRUNCATE TABLE sys.menu RESTART IDENTITY CASCADE;

-- ============================================================
-- Dashboard 模块（ID: 1-4）
-- ============================================================
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1, 0, 1, 'Dashboard', '/dashboard', '/index/index', '', 'ri:pie-chart-line', 'menus.dashboard.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (2, 1, 1, 'Console', 'console', '/dashboard/console', '', 'ri:home-smile-2-line', 'menus.dashboard.console', '', false, false, false, false, false, false, true, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (3, 1, 1, 'Analysis', 'analysis', '/dashboard/analysis', '', 'ri:align-item-bottom-line', 'menus.dashboard.analysis', '', false, false, false, false, false, false, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (4, 1, 1, 'Ecommerce', 'ecommerce', '/dashboard/ecommerce', '', 'ri:bar-chart-box-line', 'menus.dashboard.ecommerce', '', false, false, false, false, false, false, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- System 模块（ID: 100-178）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (100, 0, 1, 'System', '/system', '/index/index', '', 'ri:user-3-line', 'menus.system.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (101, 100, 1, 'User', 'user', '/system/user', '', 'ri:user-line', 'menus.system.user', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (102, 100, 1, 'Role', 'role', '/system/role', '', 'ri:user-settings-line', 'menus.system.role', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (103, 100, 1, 'UserCenter', 'user-center', '/system/user-center', '', 'ri:user-line', 'menus.system.userCenter', '', false, true, true, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (104, 100, 1, 'Menus', 'menu', '/system/menu', '', 'ri:menu-line', 'menus.system.menu', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (176, 100, 1, 'ResourcePermission', 'resource-permission', '/system/resource-permission', '', 'ri:shield-keyhole-line', 'menus.system.resourcePermission', '', false, false, false, false, false, true, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (178, 100, 1, 'SystemFeedback', 'feedback', '/system/feedback', '', 'ri:chat-3-line', 'menus.system.feedback', '', false, false, false, false, false, true, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (126, 100, 1, 'Config', 'config', '/system/config', '', 'ri:settings-3-line', 'menus.system.config', '', false, false, false, false, false, true, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (127, 100, 1, 'Notice', 'notice', '/system/notice', '', 'ri:notification-3-line', 'menus.system.notice', '', false, false, false, false, false, true, false, false, '', '', '', '', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (128, 100, 1, 'UserNotice', 'notice-center', '/system/user-notice', '', '', 'menus.system.noticeCenter', '', false, true, false, false, false, true, false, false, '', '', '', '', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (129, 100, 1, 'UserNoticeDetail', 'notice-center/:id', '/system/user-notice/detail', '', '', 'menus.system.noticeDetail', '', false, true, false, false, false, false, false, false, '', '/system/notice-center', '', '', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (130, 100, 1, 'Online', 'online', '/system/online', '', 'ri:user-shared-line', 'menus.system.online', '', false, false, false, false, false, true, false, false, '', '', '', '', 11, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (131, 100, 1, 'Dict', 'dict', '/system/dict', '', 'ri:book-2-line', 'menus.system.dict', '', false, false, false, false, false, true, false, false, '', '', '', '', 12, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (132, 100, 1, 'LoginLog', 'login-log', '/system/login-log', '', 'ri:file-list-3-line', 'menus.system.loginLog', '', false, false, false, false, false, true, false, false, '', '', '', '', 13, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (133, 100, 1, 'OperationLog', 'operation-log', '/system/operation-log', '', 'ri:file-text-line', 'menus.system.operationLog', '', false, false, false, false, false, true, false, false, '', '', '', '', 14, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (105, 104, 2, '', '', '', '', '', '新增', '', false, false, false, false, false, false, false, false, '', '', '新增', 'add', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (106, 104, 2, '', '', '', '', '', '编辑', '', false, false, false, false, false, false, false, false, '', '', '编辑', 'edit', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (107, 104, 2, '', '', '', '', '', '删除', '', false, false, false, false, false, false, false, false, '', '', '删除', 'delete', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (116, 101, 2, '', '', '', '', '', '查询用户', '', false, false, false, false, false, false, false, false, '', '', '查询用户', 'system:user:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (117, 101, 2, '', '', '', '', '', '新增用户', '', false, false, false, false, false, false, false, false, '', '', '新增用户', 'system:user:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (118, 101, 2, '', '', '', '', '', '编辑用户', '', false, false, false, false, false, false, false, false, '', '', '编辑用户', 'system:user:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (119, 101, 2, '', '', '', '', '', '删除用户', '', false, false, false, false, false, false, false, false, '', '', '删除用户', 'system:user:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (120, 101, 2, '', '', '', '', '', '重置用户密码', '', false, false, false, false, false, false, false, false, '', '', '重置用户密码', 'system:user:reset-password', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (121, 102, 2, '', '', '', '', '', '查询角色', '', false, false, false, false, false, false, false, false, '', '', '查询角色', 'system:role:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (122, 102, 2, '', '', '', '', '', '新增角色', '', false, false, false, false, false, false, false, false, '', '', '新增角色', 'system:role:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (123, 102, 2, '', '', '', '', '', '编辑角色', '', false, false, false, false, false, false, false, false, '', '', '编辑角色', 'system:role:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (124, 102, 2, '', '', '', '', '', '删除角色', '', false, false, false, false, false, false, false, false, '', '', '删除角色', 'system:role:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (125, 102, 2, '', '', '', '', '', '角色权限', '', false, false, false, false, false, false, false, false, '', '', '角色权限', 'system:role:permission', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (134, 104, 2, '', '', '', '', '', '查询菜单', '', false, false, false, false, false, false, false, false, '', '', '查询菜单', 'system:menu:list', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (135, 104, 2, '', '', '', '', '', '新增菜单', '', false, false, false, false, false, false, false, false, '', '', '新增菜单', 'system:menu:create', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (136, 104, 2, '', '', '', '', '', '编辑菜单', '', false, false, false, false, false, false, false, false, '', '', '编辑菜单', 'system:menu:update', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (137, 104, 2, '', '', '', '', '', '删除菜单', '', false, false, false, false, false, false, false, false, '', '', '删除菜单', 'system:menu:delete', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (138, 104, 2, '', '', '', '', '', '新增按钮', '', false, false, false, false, false, false, false, false, '', '', '新增按钮', 'system:button:create', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (139, 104, 2, '', '', '', '', '', '编辑按钮', '', false, false, false, false, false, false, false, false, '', '', '编辑按钮', 'system:button:update', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (177, 104, 2, '', '', '', '', '', '绑定资源', '', false, false, false, false, false, false, false, false, '', '', '绑定资源', 'bind', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (170, 176, 2, '', '', '', '', '', '查询资源', '', false, false, false, false, false, false, false, false, '', '', '查询资源', 'system:resource:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (171, 176, 2, '', '', '', '', '', '新增资源', '', false, false, false, false, false, false, false, false, '', '', '新增资源', 'system:resource:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (172, 176, 2, '', '', '', '', '', '编辑资源', '', false, false, false, false, false, false, false, false, '', '', '编辑资源', 'system:resource:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (173, 176, 2, '', '', '', '', '', '删除资源', '', false, false, false, false, false, false, false, false, '', '', '删除资源', 'system:resource:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (174, 176, 2, '', '', '', '', '', '绑定资源', '', false, false, false, false, false, false, false, false, '', '', '绑定资源', 'system:resource:bind', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (175, 176, 2, '', '', '', '', '', '刷新资源权限', '', false, false, false, false, false, false, false, false, '', '', '刷新资源权限', 'system:resource:reload', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (140, 126, 2, '', '', '', '', '', '查询配置', '', false, false, false, false, false, false, false, false, '', '', '查询配置', 'system:config:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (141, 126, 2, '', '', '', '', '', '新增配置', '', false, false, false, false, false, false, false, false, '', '', '新增配置', 'system:config:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (142, 126, 2, '', '', '', '', '', '编辑配置', '', false, false, false, false, false, false, false, false, '', '', '编辑配置', 'system:config:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (143, 126, 2, '', '', '', '', '', '删除配置', '', false, false, false, false, false, false, false, false, '', '', '删除配置', 'system:config:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (144, 126, 2, '', '', '', '', '', '查询配置分组', '', false, false, false, false, false, false, false, false, '', '', '查询配置分组', 'system:config-group:list', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (145, 126, 2, '', '', '', '', '', '新增配置分组', '', false, false, false, false, false, false, false, false, '', '', '新增配置分组', 'system:config-group:create', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (146, 126, 2, '', '', '', '', '', '编辑配置分组', '', false, false, false, false, false, false, false, false, '', '', '编辑配置分组', 'system:config-group:update', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (147, 126, 2, '', '', '', '', '', '删除配置分组', '', false, false, false, false, false, false, false, false, '', '', '删除配置分组', 'system:config-group:delete', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (148, 127, 2, '', '', '', '', '', '查询公告', '', false, false, false, false, false, false, false, false, '', '', '查询公告', 'system:notice:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (149, 127, 2, '', '', '', '', '', '新增公告', '', false, false, false, false, false, false, false, false, '', '', '新增公告', 'system:notice:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (150, 127, 2, '', '', '', '', '', '编辑公告', '', false, false, false, false, false, false, false, false, '', '', '编辑公告', 'system:notice:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (151, 127, 2, '', '', '', '', '', '删除公告', '', false, false, false, false, false, false, false, false, '', '', '删除公告', 'system:notice:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (152, 127, 2, '', '', '', '', '', '发布公告', '', false, false, false, false, false, false, false, false, '', '', '发布公告', 'system:notice:publish', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (153, 127, 2, '', '', '', '', '', '撤回公告', '', false, false, false, false, false, false, false, false, '', '', '撤回公告', 'system:notice:revoke', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (154, 127, 2, '', '', '', '', '', '置顶公告', '', false, false, false, false, false, false, false, false, '', '', '置顶公告', 'system:notice:pin', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (155, 128, 2, '', '', '', '', '', '查询通知中心', '', false, false, false, false, false, false, false, false, '', '', '查询通知中心', 'system:user-notice:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (156, 128, 2, '', '', '', '', '', '读取通知', '', false, false, false, false, false, false, false, false, '', '', '读取通知', 'system:user-notice:read', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (157, 130, 2, '', '', '', '', '', '查询在线用户', '', false, false, false, false, false, false, false, false, '', '', '查询在线用户', 'system:online:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (158, 130, 2, '', '', '', '', '', '强制下线', '', false, false, false, false, false, false, false, false, '', '', '强制下线', 'system:online:kick', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (159, 131, 2, '', '', '', '', '', '查询字典类型', '', false, false, false, false, false, false, false, false, '', '', '查询字典类型', 'system:dict-type:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (160, 131, 2, '', '', '', '', '', '新增字典类型', '', false, false, false, false, false, false, false, false, '', '', '新增字典类型', 'system:dict-type:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (161, 131, 2, '', '', '', '', '', '编辑字典类型', '', false, false, false, false, false, false, false, false, '', '', '编辑字典类型', 'system:dict-type:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (162, 131, 2, '', '', '', '', '', '删除字典类型', '', false, false, false, false, false, false, false, false, '', '', '删除字典类型', 'system:dict-type:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (163, 131, 2, '', '', '', '', '', '查询字典数据', '', false, false, false, false, false, false, false, false, '', '', '查询字典数据', 'system:dict-data:list', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (164, 131, 2, '', '', '', '', '', '新增字典数据', '', false, false, false, false, false, false, false, false, '', '', '新增字典数据', 'system:dict-data:create', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (165, 131, 2, '', '', '', '', '', '编辑字典数据', '', false, false, false, false, false, false, false, false, '', '', '编辑字典数据', 'system:dict-data:update', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (166, 131, 2, '', '', '', '', '', '删除字典数据', '', false, false, false, false, false, false, false, false, '', '', '删除字典数据', 'system:dict-data:delete', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (167, 132, 2, '', '', '', '', '', '查询登录日志', '', false, false, false, false, false, false, false, false, '', '', '查询登录日志', 'system:login-log:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (168, 133, 2, '', '', '', '', '', '查询操作日志', '', false, false, false, false, false, false, false, false, '', '', '查询操作日志', 'system:operation-log:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (169, 133, 2, '', '', '', '', '', '查看操作日志', '', false, false, false, false, false, false, false, false, '', '', '查看操作日志', 'system:operation-log:detail', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (108, 100, 1, 'Nested', 'nested', '', '', 'ri:menu-unfold-3-line', 'menus.system.nested', '', false, false, false, false, false, true, false, false, '', '', '', '', 13, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (109, 108, 1, 'NestedMenu1', 'menu1', '/system/nested/menu1', '', 'ri:align-justify', 'menus.system.menu1', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (110, 108, 1, 'NestedMenu2', 'menu2', '', '', 'ri:align-justify', 'menus.system.menu2', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (111, 110, 1, 'NestedMenu2-1', 'menu2-1', '/system/nested/menu2', '', 'ri:align-justify', 'menus.system.menu21', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (112, 108, 1, 'NestedMenu3', 'menu3', '', '', 'ri:align-justify', 'menus.system.menu3', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (113, 112, 1, 'NestedMenu3-1', 'menu3-1', '/system/nested/menu3', '', '', 'menus.system.menu31', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (114, 112, 1, 'NestedMenu3-2', 'menu3-2', '', '', '', 'menus.system.menu32', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (115, 114, 1, 'NestedMenu3-2-1', 'menu3-2-1', '/system/nested/menu3/menu3-2', '', '', 'menus.system.menu321', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Article 模块（ID: 200-207）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (200, 0, 1, 'Article', '/article', '/index/index', '', 'ri:book-2-line', 'menus.article.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (201, 200, 1, 'ArticleList', 'article-list', '/article/list', '', 'ri:article-line', 'menus.article.articleList', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (202, 201, 2, '', '', '', '', '', '新增', '', false, false, false, false, false, false, false, false, '', '', '新增', 'add', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (203, 201, 2, '', '', '', '', '', '编辑', '', false, false, false, false, false, false, false, false, '', '', '编辑', 'edit', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (204, 200, 1, 'ArticleDetail', 'detail/:id', '/article/detail', '', '', 'menus.article.articleDetail', '', false, true, false, false, false, true, false, false, '', '/article/article-list', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (205, 200, 1, 'ArticleComment', 'comment', '/article/comment', '', 'ri:mail-line', 'menus.article.comment', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (206, 200, 1, 'ArticlePublish', 'publish', '/article/publish', '', 'ri:telegram-2-line', 'menus.article.articlePublish', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (207, 206, 2, '', '', '', '', '', '发布', '', false, false, false, false, false, false, false, false, '', '', '发布', 'add', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Template 模块（ID: 300-307）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (300, 0, 1, 'Template', '/template', '/index/index', '', 'ri:apps-2-line', 'menus.template.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (301, 300, 1, 'Cards', 'cards', '/template/cards', '', 'ri:wallet-line', 'menus.template.cards', '', false, false, false, false, false, false, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (302, 300, 1, 'Banners', 'banners', '/template/banners', '', 'ri:rectangle-line', 'menus.template.banners', '', false, false, false, false, false, false, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (303, 300, 1, 'Charts', 'charts', '/template/charts', '', 'ri:bar-chart-box-line', 'menus.template.charts', '', false, false, false, false, false, false, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (304, 300, 1, 'Map', 'map', '/template/map', '', 'ri:map-pin-line', 'menus.template.map', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (305, 300, 1, 'Chat', 'chat', '/template/chat', '', 'ri:message-3-line', 'menus.template.chat', '', false, false, false, false, false, true, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (306, 300, 1, 'Calendar', 'calendar', '/template/calendar', '', 'ri:calendar-2-line', 'menus.template.calendar', '', false, false, false, false, false, true, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (307, 300, 1, 'Pricing', 'pricing', '/template/pricing', '', 'ri:money-cny-box-line', 'menus.template.pricing', '', false, false, false, true, false, true, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Widgets 模块（ID: 400-415）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (400, 0, 1, 'Widgets', '/widgets', '/index/index', '', 'ri:apps-2-add-line', 'menus.widgets.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (401, 400, 1, 'Icon', 'icon', '/widgets/icon', '', 'ri:palette-line', 'menus.widgets.icon', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (402, 400, 1, 'ImageCrop', 'image-crop', '/widgets/image-crop', '', 'ri:screenshot-line', 'menus.widgets.imageCrop', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (403, 400, 1, 'Excel', 'excel', '/widgets/excel', '', 'ri:download-2-line', 'menus.widgets.excel', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (404, 400, 1, 'Video', 'video', '/widgets/video', '', 'ri:vidicon-line', 'menus.widgets.video', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (405, 400, 1, 'CountTo', 'count-to', '/widgets/count-to', '', 'ri:anthropic-line', 'menus.widgets.countTo', '', false, false, false, false, false, false, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (406, 400, 1, 'WangEditor', 'wang-editor', '/widgets/wang-editor', '', 'ri:t-box-line', 'menus.widgets.wangEditor', '', false, false, false, false, false, true, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (407, 400, 1, 'Watermark', 'watermark', '/widgets/watermark', '', 'ri:water-flash-line', 'menus.widgets.watermark', '', false, false, false, false, false, true, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (408, 400, 1, 'ContextMenu', 'context-menu', '/widgets/context-menu', '', 'ri:menu-2-line', 'menus.widgets.contextMenu', '', false, false, false, false, false, true, false, false, '', '', '', '', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (409, 400, 1, 'Qrcode', 'qrcode', '/widgets/qrcode', '', 'ri:qr-code-line', 'menus.widgets.qrcode', '', false, false, false, false, false, true, false, false, '', '', '', '', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (410, 400, 1, 'Drag', 'drag', '/widgets/drag', '', 'ri:drag-move-fill', 'menus.widgets.drag', '', false, false, false, false, false, true, false, false, '', '', '', '', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (411, 400, 1, 'WidgetsDataSelect', 'data-select', '/widgets/data-select', '', 'ri:list-check-3', 'menus.widgets.dataSelect', '', false, false, false, false, false, true, false, false, '', '', '', '', 11, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (412, 400, 1, 'WidgetsResourceSelect', 'resource-select', '/widgets/resource-select', '', 'ri:folder-image-line', 'menus.widgets.resourceSelect', '', false, false, false, false, false, true, false, false, '', '', '', '', 12, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (413, 400, 1, 'TextScroll', 'text-scroll', '/widgets/text-scroll', '', 'ri:input-method-line', 'menus.widgets.textScroll', '', false, false, false, false, false, true, false, false, '', '', '', '', 13, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (414, 400, 1, 'Fireworks', 'fireworks', '/widgets/fireworks', '', 'ri:magic-line', 'menus.widgets.fireworks', '', false, false, false, false, false, true, false, false, 'Hot', '', '', '', 14, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (415, 400, 1, 'ElementUI', '/outside/iframe/elementui', '', '', 'ri:apps-2-line', 'menus.widgets.elementUI', 'https://element-plus.org/zh-CN/component/overview.html', true, false, false, false, false, false, false, false, '', '', '', '', 15, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Examples 模块（ID: 500-519）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (500, 0, 1, 'Examples', '/examples', '/index/index', '', 'ri:sparkling-line', 'menus.examples.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (501, 500, 1, 'Permission', 'permission', '', '', 'ri:fingerprint-line', 'menus.examples.permission.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (502, 501, 1, 'PermissionSwitchRole', 'switch-role', '/examples/permission/switch-role', '', 'ri:contacts-line', 'menus.examples.permission.switchRole', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (503, 501, 1, 'PermissionButtonAuth', 'button-auth', '/examples/permission/button-auth', '', 'ri:mouse-line', 'menus.examples.permission.buttonAuth', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (504, 503, 2, '', '', '', '', '', '新增', '', false, false, false, false, false, false, false, false, '', '', '新增', 'add', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (505, 503, 2, '', '', '', '', '', '编辑', '', false, false, false, false, false, false, false, false, '', '', '编辑', 'edit', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (506, 503, 2, '', '', '', '', '', '删除', '', false, false, false, false, false, false, false, false, '', '', '删除', 'delete', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (507, 503, 2, '', '', '', '', '', '导出', '', false, false, false, false, false, false, false, false, '', '', '导出', 'export', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (508, 503, 2, '', '', '', '', '', '查看', '', false, false, false, false, false, false, false, false, '', '', '查看', 'view', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (509, 503, 2, '', '', '', '', '', '发布', '', false, false, false, false, false, false, false, false, '', '', '发布', 'publish', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (510, 503, 2, '', '', '', '', '', '配置', '', false, false, false, false, false, false, false, false, '', '', '配置', 'config', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (511, 503, 2, '', '', '', '', '', '管理', '', false, false, false, false, false, false, false, false, '', '', '管理', 'manage', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (512, 501, 1, 'PermissionPageVisibility', 'page-visibility', '/examples/permission/page-visibility', '', 'ri:user-3-line', 'menus.examples.permission.pageVisibility', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (513, 500, 1, 'Tabs', 'tabs', '/examples/tabs', '', 'ri:price-tag-line', 'menus.examples.tabs', '', false, false, false, false, false, false, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (514, 500, 1, 'TablesBasic', 'tables/basic', '/examples/tables/basic', '', 'ri:layout-grid-line', 'menus.examples.tablesBasic', '', false, false, false, false, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (515, 500, 1, 'Tables', 'tables', '/examples/tables', '', 'ri:table-3', 'menus.examples.tables', '', false, false, false, false, false, true, false, false, '', '', '', '', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (516, 500, 1, 'Forms', 'forms', '/examples/forms', '', 'ri:table-view', 'menus.examples.forms', '', false, false, false, false, false, true, false, false, '', '', '', '', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (517, 500, 1, 'SearchBar', 'form/search-bar', '/examples/forms/search-bar', '', 'ri:table-line', 'menus.examples.searchBar', '', false, false, false, false, false, true, false, false, '', '', '', '', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (518, 500, 1, 'TablesTree', 'tables/tree', '/examples/tables/tree', '', 'ri:layout-2-line', 'menus.examples.tablesTree', '', false, false, false, false, false, true, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (519, 500, 1, 'SocketChat', 'socket-chat', '/examples/socket-chat', '', 'ri:shake-hands-line', 'menus.examples.socketChat', '', false, false, false, false, false, true, false, false, 'New', '', '', '', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Result 模块（ID: 600-602）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (600, 0, 1, 'Result', '/result', '/index/index', '', 'ri:checkbox-circle-line', 'menus.result.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (601, 600, 1, 'ResultSuccess', 'success', '/result/success', '', 'ri:checkbox-circle-line', 'menus.result.success', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (602, 600, 1, 'ResultFail', 'fail', '/result/fail', '', 'ri:close-circle-line', 'menus.result.fail', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Exception 模块（ID: 700-703）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (700, 0, 1, 'Exception', '/exception', '/index/index', '', 'ri:error-warning-line', 'menus.exception.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (701, 700, 1, 'Exception403', '403', '/exception/403', '', '', 'menus.exception.forbidden', '', false, false, true, true, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (702, 700, 1, 'Exception404', '404', '/exception/404', '', '', 'menus.exception.notFound', '', false, false, true, true, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (703, 700, 1, 'Exception500', '500', '/exception/500', '', '', 'menus.exception.serverError', '', false, false, true, true, false, true, false, false, '', '', '', '', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Safeguard 模块（ID: 800-801）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (800, 0, 1, 'Safeguard', '/safeguard', '/index/index', '', 'ri:shield-check-line', 'menus.safeguard.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (801, 800, 1, 'SafeguardServer', 'server', '/safeguard/server', '', 'ri:hard-drive-3-line', 'menus.safeguard.server', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (802, 801, 2, '', '', '', '', '', '查询服务器监控', '', false, false, false, false, false, false, false, false, '', '', '查询服务器监控', 'system:monitor:server', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (803, 801, 2, '', '', '', '', '', '查询缓存监控', '', false, false, false, false, false, false, false, false, '', '', '查询缓存监控', 'system:monitor:cache', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (804, 801, 2, '', '', '', '', '', '清理缓存', '', false, false, false, false, false, false, false, false, '', '', '清理缓存', 'system:monitor:cache-delete', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Scheduler 模块（ID: 1000-1010）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1000, 0, 1, 'Scheduler', '/scheduler', '/index/index', '', 'ri:timer-line', 'menus.scheduler.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1001, 1000, 1, 'SchedulerJob', 'job', '/scheduler/job', '', 'ri:list-check-2', 'menus.scheduler.job', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1002, 1000, 1, 'SchedulerRun', 'run', '/scheduler/run', '', 'ri:history-line', 'menus.scheduler.run', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1003, 1001, 2, '', '', '', '', '', '查询任务', '', false, false, false, false, false, false, false, false, '', '', '查询任务', 'scheduler:job:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1004, 1001, 2, '', '', '', '', '', '新增任务', '', false, false, false, false, false, false, false, false, '', '', '新增任务', 'scheduler:job:create', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1005, 1001, 2, '', '', '', '', '', '编辑任务', '', false, false, false, false, false, false, false, false, '', '', '编辑任务', 'scheduler:job:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1006, 1001, 2, '', '', '', '', '', '启停任务', '', false, false, false, false, false, false, false, false, '', '', '启停任务', 'scheduler:job:toggle', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1007, 1001, 2, '', '', '', '', '', '触发任务', '', false, false, false, false, false, false, false, false, '', '', '触发任务', 'scheduler:job:trigger', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1008, 1001, 2, '', '', '', '', '', '删除任务', '', false, false, false, false, false, false, false, false, '', '', '删除任务', 'scheduler:job:delete', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1009, 1002, 2, '', '', '', '', '', '查询执行记录', '', false, false, false, false, false, false, false, false, '', '', '查询执行记录', 'scheduler:run:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1010, 1002, 2, '', '', '', '', '', '查看执行记录', '', false, false, false, false, false, false, false, false, '', '', '查看执行记录', 'scheduler:run:detail', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- File 模块（ID: 1100-1111）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1100, 0, 1, 'File', '/file', '/index/index', '', 'ri:folder-3-line', 'menus.file.title', '', false, false, false, false, false, false, false, false, '', '', '', '', 11, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1101, 1100, 1, 'FileManage', 'manage', '/file/manage', '', 'ri:file-list-3-line', 'menus.file.manage', '', false, false, false, false, false, true, false, false, '', '', '', '', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1102, 1100, 1, 'FileExamples', 'examples', '/file/examples', '', 'ri:upload-cloud-2-line', 'menus.file.examples', '', false, false, false, false, false, true, false, false, '', '', '', '', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1103, 1101, 2, '', '', '', '', '', '查询文件', '', false, false, false, false, false, false, false, false, '', '', '查询文件', 'file:manage:list', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1104, 1101, 2, '', '', '', '', '', '上传文件', '', false, false, false, false, false, false, false, false, '', '', '上传文件', 'file:manage:upload', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1105, 1101, 2, '', '', '', '', '', '编辑文件', '', false, false, false, false, false, false, false, false, '', '', '编辑文件', 'file:manage:update', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1106, 1101, 2, '', '', '', '', '', '删除文件', '', false, false, false, false, false, false, false, false, '', '', '删除文件', 'file:manage:delete', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1107, 1101, 2, '', '', '', '', '', '分享文件', '', false, false, false, false, false, false, false, false, '', '', '分享文件', 'file:manage:share', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1108, 1101, 2, '', '', '', '', '', '新增目录', '', false, false, false, false, false, false, false, false, '', '', '新增目录', 'file:folder:create', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1109, 1101, 2, '', '', '', '', '', '编辑目录', '', false, false, false, false, false, false, false, false, '', '', '编辑目录', 'file:folder:update', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1110, 1101, 2, '', '', '', '', '', '删除目录', '', false, false, false, false, false, false, false, false, '', '', '删除目录', 'file:folder:delete', 8, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (1111, 1101, 2, '', '', '', '', '', '下载文件', '', false, false, false, false, false, false, false, false, '', '', '下载文件', 'file:manage:download', 9, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- Help 模块（ID: 900-903）
-- ============================================================

INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (900, 0, 1, 'Document', '', '', '', 'ri:bill-line', 'menus.help.document', 'https://docs.example.com', false, false, false, false, false, false, false, false, '', '', '', '', 13, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (901, 0, 1, 'LiteVersion', '', '', '', 'ri:bus-2-line', 'menus.help.liteVersion', 'https://lite.example.com', false, false, false, false, false, false, false, false, '', '', '', '', 14, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (902, 0, 1, 'OldVersion', '', '', '', 'ri:subway-line', 'menus.help.oldVersion', 'https://old.example.com', false, false, false, false, false, false, false, false, '', '', '', '', 15, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys.menu (id, parent_id, menu_type, name, path, component, redirect, icon, title, link, is_iframe, is_hide, is_hide_tab, is_full_page, is_first_level, keep_alive, fixed_tab, show_badge, show_text_badge, active_path, auth_name, auth_mark, sort, enabled, create_time, update_time) VALUES (903, 0, 1, 'ChangeLog', '/change/log', '/change/log', '', 'ri:gamepad-line', 'menus.plan.log', '', false, false, false, false, false, false, false, false, 'v3.0.1', '', '', '', 16, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================
-- 重置序列
-- ============================================================

-- 回填按钮权限位图位置
WITH missing_bit_positions AS (
    SELECT
        id,
        (
            COALESCE(
                (SELECT MAX(bit_position) + 1 FROM sys.menu WHERE menu_type = 2 AND bit_position IS NOT NULL),
                0
            ) + ROW_NUMBER() OVER (ORDER BY id) - 1
        )::INTEGER AS next_bit_position
    FROM sys.menu
    WHERE menu_type = 2 AND bit_position IS NULL
)
UPDATE sys.menu AS m
SET bit_position = missing_bit_positions.next_bit_position
FROM missing_bit_positions
WHERE m.id = missing_bit_positions.id;

SELECT setval('sys.menu_id_seq', (SELECT MAX(id) FROM sys.menu));
