[package]
edition.workspace = true
name = "summer-domain"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
schemars = { workspace = true }
sea-orm = { workspace = true, features = [
    "with-chrono",
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
serde = { workspace = true, features = ["derive"] }
summer-common = { workspace = true }
summer-system-model = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
