//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "sys", table_name = "tenant")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub tenant_id: String,
    pub tenant_name: String,
    pub default_isolation_level: i16,
    pub contact_name: String,
    pub contact_email: String,
    pub contact_phone: String,
    pub expire_time: Option<DateTime>,
    pub status: i16,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub metadata: Json,
    pub remark: String,
    pub create_by: String,
    pub create_time: DateTime,
    pub update_by: String,
    pub update_time: DateTime,
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let now = chrono::Local::now().naive_local();
        self.update_time = Set(now);
        if insert {
            self.create_time = Set(now);
        }
        Ok(self)
    }
}
