//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "sys", table_name = "tenant_datasource")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub tenant_id: String,
    pub isolation_level: i16,
    pub status: String,
    pub schema_name: Option<String>,
    pub datasource_name: Option<String>,
    pub db_uri: Option<String>,
    pub db_max_conns: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub readonly_config: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra_config: Json,
    pub last_sync_time: Option<DateTime>,
    pub remark: String,
    pub create_by: String,
    pub create_time: DateTime,
    pub update_by: String,
    pub update_time: DateTime,
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let now = chrono::Local::now().naive_local();
        self.update_time = Set(now);
        if insert {
            self.create_time = Set(now);
        }
        Ok(self)
    }
}
